BlogApp.WebUI/Controllers/BlogController.cs
using BlogApp.Data.Abstract;
using BlogApp.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.Controllers
{
    public class BlogController : Controller
    {
        private IBlogRepository _blogRepository;
        private ICategoryRepository _categoryRepository;

        public BlogController(IBlogRepository blogrepo, ICategoryRepository categoryrepo)
        {
            _blogRepository = blogrepo;
            _categoryRepository = categoryrepo;
        }

        public IActionResult Index(int? id,string q)
        {
                var query = _blogRepository.GetAll().Where(i => i.isApproved == true);
                if (id != null)
                {
                    query = query.Where(i => i.CategoryId == id);
                }

                if (!string.IsNullOrEmpty(q)) //burdan gelen q null ya da boşluk karakterine eşit değil ise
                {
                query = query.Where(i => i.Title.Contains(q) || i.Description.Contains(q) || i.Body.Contains(q)); //3 farklı yerde arama yapıyoruz bunlardan herhangi biri true dönerse ilgili olan kayıt gelir
                }

                return View(query.OrderByDescending(i => i.Date));   
        }

        public IActionResult Details(int id)
        {
            return View(_blogRepository.GetById(id));
        }

        public IActionResult List()
        {
            //repository.GetAll() ile bir blog listesi gönderiyoruz
            return View(_blogRepository.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Blog entity)
        {
            //blog kayıtın zamanına kayıt zamanı ataması
            entity.Date = DateTime.Now;

            if (ModelState.IsValid) //Validasyon gerekliliklerini geçmişse
            {
                _blogRepository.AddBlog(entity);
                return RedirectToAction("List");
            }
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "Id", "Name");
            return View(entity);
        }

        [HttpGet]
        public IActionResult Edit(int id) //dışarıdan bir id almalı gönderdiğim id'ye göre sorgulama yapıp veritabından seçtiğim veriyi form üzerine gönderebilmeliyim
        {
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "Id", "Name");
            return View(_blogRepository.GetById(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Blog entity,IFormFile file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    //kayıt resmi için
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", file.FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                        //tabi entity Image'i de kaydedelim
                        entity.Image = file.FileName;
                    }
                }

                _blogRepository.UpdateBlog(entity);
                //ekleme işlemi yapılır List view'ine kullanıcı yönlendirilir, mesajda gönderilir
                TempData["message"] = $"{entity.Title} güncellendi";
                return RedirectToAction("List");
            }
            //eğer bir problem varsa problemli entity'i kullanıcıya gösterelim
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "Id", "Name");
            return View(entity);

        }

        [HttpGet]
        public IActionResult AddOrUpdate(int? id) //id nullable çünkü yeni bir kayıt yaparsam buraya id gelmeyecek güncelleme işlemi ise id olacak
        {
            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "Id", "Name");

            if (id == null)
            {
                //yeni kayıt  
                return View(new Blog()); //içerisinde yeni blog elemanı göndermeliyiz (Id oto 0 atanır)
            }
            else
            {
                //güncelleme
                return View(_blogRepository.GetById((int)id)); //id nullable olduğu için int cast edildi
            }
        }

        [HttpPost]
        public IActionResult AddOrUpdate(Blog entity)
        {
            if (ModelState.IsValid)
            {
                _blogRepository.SaveBlog(entity);
                TempData["message"] = $"{entity.Title} kayıt edildi";
                return RedirectToAction("List");
            }

            ViewBag.Categories = new SelectList(_categoryRepository.GetAll(), "Id", "Name");
            return View(entity);
        }

        [HttpGet]
        public IActionResult Delete(int id) //list'den delete butonuna basılınca id ile gelir
        {
            return View(_blogRepository.GetById(id));
            //gelen id ile kayıtı alır form üzerine aktarırız
        }


        [HttpPost,ActionName("Delete")] //get ve post actionların imzası aynı olacağından hatanın önüne geçmek için post kısmını DeleteConfirmed yaparsak
        //ve ActionName("Delete") diye parametre olarak verirsek hatayı önleriz
        public IActionResult DeleteConfirmed(int id) 
        {
            _blogRepository.DeleteBlog(id);
            TempData["message"] = $"{id} numaralı kayıt silindi";
            return RedirectToAction("List");
        }

    }
}

BlogApp.WebUI/ViewComponents/CategoryMenuViewComponent.cs
using BlogApp.Data.Abstract;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.WebUI.ViewComponents
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        private ICategoryRepository _repository;

        public CategoryMenuViewComponent(ICategoryRepository repo)
        {
            _repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            //seçilen kategorinin id'si alınıp daha sonra active class'ı verilecek, RouteData nullable
            ViewBag.SelectedCategory = RouteData?.Values["id"];
            //bütün kategori bilgilerini view üzerine taşıdık
            return View(_repository.GetAll());
        }
    }
}

BlogApp.WebUI/Views/Blog/AddOrUpdate.cshtml
@model Blog

@{
    ViewData["Title"] = "Edit";
}

<div class="container mt-3">
    <h2>Edit Blog</h2>
    <hr />
    <form asp-controller="Blog" asp-action="Edit" method="post">

        @* update işleminde hidden input olarak id bilgisi de gerekli *@
        <input type="hidden" asp-for="Id" />

        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="Description">Description</label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>

        <div class="form-group">
            <label asp-for="Body">Body</label>
            <textarea asp-for="Body" class="form-control"></textarea>
        </div>


        <div class="form-group">
            <label asp-for="Image"></label>
            <input asp-for="Image" class="form-control" />
        </div>

        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isHome" class="form-check-input" />
                is Home
            </label>
        </div>

        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isApproved" class="form-check-input" />
                is Approved
            </label>
        </div>

        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isSlider" class="form-check-input" />
                is Slider
            </label>
        </div>

        <div class="form-group">
            <label asp-for="CategoryId"></label>
            <select asp-for="CategoryId" asp-items="ViewBag.Categories" class="form-control">
                <option disabled selected value="">Select Category</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Kaydet</button>
    </form>
</div>

BlogApp.WebUI/Views/Blog/Create.cshtml
@model Blog

@{
    ViewData["Title"] = "Create";
    Layout = "_AdminLayout";
}

<div class="container mt-3">
    <h2>Create Blog</h2>
    <hr />
    <form asp-controller="Blog" asp-action="Create" method="post">

        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="Description">Description</label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>

        <div class="form-group">
            <label asp-for="Body">Body</label>
            <textarea asp-for="Body" class="form-control"></textarea>
        </div>


        <div class="form-group">
            <label asp-for="Image"></label>
            <input asp-for="Image" class="form-control" />
        </div>


        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isHome" class="form-check-input" />
                is Home
            </label>
        </div>

        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isApproved" class="form-check-input" />
                is Approved
            </label>
        </div>

        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isSlider" class="form-check-input" />
                is Slider
            </label>
        </div>

        <div class="form-group">
            <label asp-for="CategoryId"></label>
            <select asp-for="CategoryId" asp-items="ViewBag.Categories" class="form-control">
                <option disabled selected value="">Select Category</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Kaydet</button>
    </form>
</div>

BlogApp.WebUI/Views/Blog/Delete.cshtml
@model Blog

@{
    ViewData["Title"] = "Delete";
    Layout = "_AdminLayout";
}

<div class="container mt-3">
    <h2>
        <b>@Model.Title</b> isimli kaydı silmek istiyor musunuz?
    </h2>

    <form asp-controller="Blog" asp-action="Delete" method="post">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
</div>

BlogApp.WebUI/Views/Blog/Details.cshtml
@model Blog

@{
    ViewData["Title"] = "Details";
}


<div class="container mt-3">
    <div class="row">

        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>

        <div class="col-md-9">
            <div class="card mb-3"> 
                <div class="card-header">
                    @Model.Title
                </div>
                <img class="card-img-top" src="~/img/@Model.Image" alt="@Model.Title" />
                <div class="card-body">
                    <h5 class="card-title">@Model.Title</h5>
                    <p class="card-text">@Model.Description</p>
                    <p class="card-text">@Html.Raw(Model.Body)</p>
                </div>
            </div>
        </div>

    </div>

</div>

BlogApp.WebUI/Views/Blog/Edit.cshtml
@model Blog

@{
    ViewData["Title"] = "Edit";
    Layout = "_AdminLayout";
}

<div class="container mt-3">
    <h2>Edit Blog</h2>
    <hr />
    <form asp-controller="Blog" asp-action="Edit" method="post" enctype="multipart/form-data">

        @* update işleminde hidden input olarak id bilgisi de gerekli *@
        <input type="hidden" asp-for="Id" />

        <input type="hidden" asp-for="Image" />

        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="Description">Description</label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>

        <div class="form-group">
            <label asp-for="Body">Body</label>
            <textarea asp-for="Body" class="form-control"></textarea>
        </div>


        <div class="form-group">
            <img src="~/img/@Model.Image" width="120" />
            <input type="file" name="file" id="file" class="form-control" />
        </div>

        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isHome" class="form-check-input" />
                is Home
            </label>
        </div>

        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isApproved" class="form-check-input" />
                is Approved
            </label>
        </div>

        <div class="form-check">
            <label class="form-check-label">
                <input asp-for="isSlider" class="form-check-input" />
                is Slider
            </label>
        </div>


        <div class="form-group">
            <label asp-for="CategoryId"></label>
            <select asp-for="CategoryId" asp-items="ViewBag.Categories" class="form-control">
                <option disabled selected value="">Select Category</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Kaydet</button>
    </form>
</div>

BlogApp.WebUI/Views/Blog/Index.cshtml
@model IEnumerable<Blog>

@{
    ViewData["Title"] = "Index";
}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <div class="col-md-9">
            @Html.Partial("_BlogList", Model) @* partial view _BlogList gidecek Model sayfanın modeli**@
        </div>
    </div>
</div>

BlogApp.WebUI/Views/Blog/List.cshtml
@model IEnumerable<Blog>

@{
    ViewData["Title"] = "List";
    Layout = "_AdminLayout";
}

<div class="container mt-3">
    <h2>Blog List</h2>
    <hr />
    <div>
        <a asp-controller="Blog" asp-action="Create" class="btn btn-primary my-2">Create</a>
    </div>
    <div class="row">
        <div class="col">
            @if (Model.Count() > 0) //burada bir blog vardır
            {
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Image</th>
                            <th>Title</th>
                            <th>Date</th>
                            <th>is Approved</th>
                            <th>is Home </th>
                            <th>is Slider</th>
                            <th></th>

                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@item.Id</td>
                            <td>
                                <img src="~/img/@item.Image" alt="Alternate Text" width="100" />
                            </td>
                            <td>@item.Title</td>
                            <td>@item.Date</td>
                            <td>
                                @if (item.isApproved)
                                {
                                    <i class="fas fa-check-circle"></i>
                                }
                                else
                                {
                                    <i class="fas fa-times-circle"></i>
                                }
                            </td>
                            <td>
                                @if (item.isHome)
                                {
                                    <i class="fas fa-check-circle"></i>
                                }
                                else
                                {
                                    <i class="fas fa-times-circle"></i>
                                }
                            </td>
                            <td>
                                @if (item.isSlider)
                                {
                                    <i class="fas fa-check-circle"></i>
                                }
                                else
                                {
                                    <i class="fas fa-times-circle"></i>
                                }
                            </td>
                            <td>
                                <a asp-controller="Blog" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary btn-sm">
                                    Edit
                                </a>
                                <a asp-controller="Blog" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">
                                    Delete
                                </a>
                            </td>

                        </tr>
                        }

                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-danger">
                    Blog Eklenmemiş
                </div>
            }
        </div>
    </div>
</div>